include:
  - project: 'asm/gitlab-ci-helpers'
    file: '/gitlab-ci-helpers.yml'

variables:
  KUBE_PROD_DOMAIN: documentation.sigma2.no # The main domain for your application.
  HTTP_PORT: '80' # The port number of the web server.
  KUBE_TEST_DOMAIN: sigma2-eksterndoc.paas2.uninett.no
  REPLICAS: '2'

stages:
  - build
  - review
  - production

build:
  stage: build
  script:
    - build
  only:
    - branches
    
production:
  extends: .production
  stage: production
  variables:
    REPLICAS: "2"  
  script:
    - deploy kubernetes/deployment.yaml
  
review:
  extends: .review
  stage: review

  script:
    - deploy kubernetes/deployment.yaml

  
stop_review:
  extends: .stop_review
  stage: review
  